# lists

date 13/01/2025

In [1]:
l=[1,2,3,4,5]

In [2]:
l[0]

1

In [4]:
l[4] #fifth element

5

In [5]:
l[-1] #also give fifth element

5

#### A list can store different data type


In [7]:
l=[1,'b', "ahgsdg", True, 1.0]

In [10]:
# create a list which start 0 and goes to 9
l= list(range(0,10)) # most likely does not use a python loop
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
l = [i for i in range(0,9)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
l=[]
for i in range(10):
    l.append(i)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
odd = [i for i in range(1,10,2)]
odd

[1, 3, 5, 7, 9]

### Tuple

In [16]:
l=[1,'b', "ahgsdg", True, 1.0]
l[1] = 'a'
print(l)
l[1] = 17.0254
l

[1, 'a', 'ahgsdg', True, 1.0]


[1, 17.0254, 'ahgsdg', True, 1.0]

In [19]:
# Tuple
t = (1, 0, 1.0, "asshkjas")
t[-1]

'asshkjas'

In [21]:
t[0] = 'a' # Tuple is immutable

TypeError: 'tuple' object does not support item assignment

# Numpy

 install numpy library first

In [22]:
import numpy as np

In [23]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [24]:
a.dtype

dtype('int64')

In [27]:
type(a)

numpy.ndarray

In [31]:
a[2] = 9.1
a

array([1, 2, 9, 4])

In [36]:
a = np.array([1, 2, 3, 4], dtype="float")
print(a.dtype)
a

float64


array([1., 2., 3., 4.])

In [33]:
a[2] = 9.1
a

array([1. , 2. , 9.1, 4. ])

In [34]:
a = np.array([1, 2, 3, 4.0])
a.dtype

dtype('float64')

In [39]:
print(a)
b = a
b[1] = 6
print('b=',b)
print('a=',a)

[1. 6. 3. 4.]
b= [1. 6. 3. 4.]
a= [1. 6. 3. 4.]


In [41]:
print(a)
b = a.copy()
b[3] = 69
print('b=',b)
print('a=',a)

[1. 6. 3. 4.]
b= [ 1.  6.  3. 69.]
a= [1. 6. 3. 4.]


## File I/O

In [42]:
with open("a.txt", "w") as f:
    f.write("skjdhsd LKD Jwjjh \n")

In [43]:
#Not recomend this
f = open("b.txt","w")
f.write("agshjhs")
f.close()

In [45]:
with open("print_formating.txt", "w") as f:
    f.write(f"{123.534:.8f}\t{10:d} \t string")